name: 'hubspot'
version: '0.20.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: dbt_hubspot  # Este nombre debe coincidir con el definido en profiles.yml

vars:

  #Base de datos y esquema de orígen (si no se definen se usa el que está en el profiles.yml)
  # hubspot_database: hubspot
  hubspot_schema: hubspot_staging

  # hubspot_database: "{{ 'hubspot_dev' if target.name == 'dev' else 'hubspot_prod' }}"
  # hubspot_schema: "{{ 'hubspot_staging' if target.name == 'dev' else 'hubspot' }}"

  #Todo estpa enabled = true por defecto #################################################################################################################
  # Marketing #########
  # hubspot_marketing_enabled: false                       # Disables all marketing models
  # hubspot_contact_enabled: false                          # Disables the contact models
  # hubspot_contact_list_enabled: false                     # Disables contact list models
  # hubspot_contact_list_member_enabled: false              # Disables contact list member models
  # hubspot_contact_property_enabled: false                 # Disables the contact property models
  # hubspot_contact_property_history_enabled: false         # Disables the contact property history models
  hubspot_email_event_enabled: false                       # Disables all email_event models and functionality
  hubspot_email_event_bounce_enabled: false
  hubspot_email_event_click_enabled: false
  hubspot_email_event_deferred_enabled: false
  hubspot_email_event_delivered_enabled: false
  hubspot_email_event_dropped_enabled: false
  hubspot_email_event_forward_enabled: false
  hubspot_email_event_open_enabled: false
  hubspot_email_event_print_enabled: false
  hubspot_email_event_sent_enabled: false
  hubspot_email_event_spam_report_enabled: false
  hubspot_email_event_status_change_enabled: false

  hubspot_contact_merge_audit_enabled: false               # Enables the use of the CONTACT_MERGE_AUDIT table (deprecated by Hubspot v3 API) for removing merged contacts in the final models.
    # If false, ~~~contacts will still be merged~~~, but using the CONTACT.property_hs_calculated_merged_vids field (introduced in v3 of the Hubspot CRM API)
    # If false, ~~~contacts will still be merged~~~, but using the CONTACT.property_hs_calculated_merged_vids field (introduced in v3 of the Hubspot CRM API)
    # Default = false

  # Sales #########
  # hubspot_sales_enabled: false                            # Disables all sales models
  # hubspot_company_enabled: false
  # hubspot_company_property_history_enabled: false         # Disables the company property history models
  # hubspot_deal_enabled: false
  # hubspot_merged_deal_enabled: false                       # Enables the merged_deal table, which will be used to filter out merged deals from the final deal models. False by default. Note that `hubspot_sales_enabled` and `hubspot_deal_enabled` must not be set to False.
  # hubspot_deal_company_enabled: false
  # hubspot_deal_contact_enabled: false
  # hubspot_deal_property_history_enabled: false            # Disables the deal property history models
  hubspot_engagement_enabled: false                       # Disables all engagement models and functionality
  hubspot_engagement_contact_enabled: false
  hubspot_engagement_company_enabled: false
  hubspot_engagement_deal_enabled: false
  hubspot_engagement_call_enabled: false
  hubspot_engagement_email_enabled: false
  hubspot_engagement_meeting_enabled: false
  hubspot_engagement_note_enabled: false
  hubspot_engagement_task_enabled: false
  # hubspot_owner_enabled: false
  hubspot_property_enabled: false                         # Disables property and property_option tables

  # Service #########
  hubspot_service_enabled: true                           # Enables all service/ticket models. Default = false
  hubspot_ticket_deal_enabled: true                       # Default = false

  ########################################################################################################################################################
  
  hubspot:
    contact: "{{ ref('stg_hubspot__contact') }}"
    contact_merge_audit: "{{ ref('stg_hubspot__contact_merge_audit') }}"
    contact_list: "{{ ref('stg_hubspot__contact_list') }}"
    contact_list_member: "{{ ref('stg_hubspot__contact_list_member') }}"
    contact_property_history: "{{ ref('stg_hubspot__contact_property_history') }}"
    company: "{{ ref('stg_hubspot__company') }}"
    company_property_history: "{{ ref('stg_hubspot__company_property_history') }}"
    deal: "{{ ref('stg_hubspot__deal') }}"
    merged_deal: "{{ ref('stg_hubspot__merged_deal') }}"
    deal_stage: "{{ ref('stg_hubspot__deal_stage') }}"
    deal_company: "{{ ref('stg_hubspot__deal_company') }}"
    deal_pipeline: "{{ ref('stg_hubspot__deal_pipeline') }}"
    deal_pipeline_stage: "{{ ref('stg_hubspot__deal_pipeline_stage') }}"
    deal_property_history: "{{ ref('stg_hubspot__deal_property_history') }}"
    owner: "{{ ref('stg_hubspot__owner') }}"
    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"
    engagement: "{{ ref('stg_hubspot__engagement') }}"
    engagement_call: "{{ ref('stg_hubspot__engagement_call') }}"
    engagement_company: "{{ ref('stg_hubspot__engagement_company') }}"
    engagement_contact: "{{ ref('stg_hubspot__engagement_contact') }}"
    engagement_deal: "{{ ref('stg_hubspot__engagement_deal') }}"
    engagement_email_cc: "{{ ref('stg_hubspot__engagement_email_cc') }}"
    engagement_email_to: "{{ ref('stg_hubspot__engagement_email_to') }}"
    engagement_email: "{{ ref('stg_hubspot__engagement_email') }}"
    engagement_meeting: "{{ ref('stg_hubspot__engagement_meeting') }}"
    engagement_note: "{{ ref('stg_hubspot__engagement_note') }}"
    engagement_task: "{{ ref('stg_hubspot__engagement_task') }}"
    ticket_company: "{{ ref('stg_hubspot__ticket_company') }}"
    ticket_contact: "{{ ref('stg_hubspot__ticket_contact') }}"
    ticket_deal: "{{ ref('stg_hubspot__ticket_deal') }}"
    ticket_engagement: "{{ ref('stg_hubspot__ticket_engagement') }}"
    ticket_pipeline: "{{ ref('stg_hubspot__ticket_pipeline') }}"
    ticket_pipeline_stage: "{{ ref('stg_hubspot__ticket_pipeline_stage') }}"
    ticket_property_history: "{{ ref('stg_hubspot__ticket_property_history') }}"
    ticket: "{{ ref('stg_hubspot__ticket') }}"

models:
  hubspot:
    +materialized: table
    #posfijo (ej:hubspot) que se agrega al esquema orígen (ej:hubspot_staging) para definir esquema destino (ej:hubspot_staging_hubspot) del model final
    +schema: hubspot
    marketing:
      intermediate:
        +materialized: ephemeral
        int_hubspot__contact_merge_adjust:
          +materialized: table
    sales:
      intermediate:
        +materialized: ephemeral
  
  hubspot_source:
    #posfijo (ej:stg_hubspot) que se agrega al esquema orígen (ej:hubspot_staging) para definir esquema destino (ej:hubspot_staging_stg_hubspot) del stg
    +schema: stg_hubspot # leave blank for just the target_schema        
